# Generated by Django 5.2.12 on 2026-03-18 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('championships', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('fastest_laps', models.IntegerField(default=0)),
                ('career_points', models.FloatField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=200)),
                ('circuit', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('race_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('championships', models.IntegerField(default=0)),
                ('team_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('color', models.CharField(default='#E10600', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('races', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('points', models.FloatField(default=0)),
                ('championship_position', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='stats.driver')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_stats', to='stats.team')),
            ],
        ),
        migrations.CreateModel(
            name='RacePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('points', models.FloatField(default=0)),
                ('race_time', models.CharField(blank=True, max_length=50, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_positions', to='stats.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='stats.raceresult')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.team')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='stats.team'),
        ),
    ]
