# Generated by Django 5.2.12 on 2026-03-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='championships',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='team_principal',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
